### ISSUE TITLE
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2

### ISSUE THREAD

**Issue by kasir-barati** [wurstmeister/zookeeper-docker#32]
Hi,

I have my compose file:

```yaml
services:
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - 9092:9092
    depends_on:
      zookeeper:
        condition: service_started
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./third-party/kafka/jaas.conf:/app/config/jaas.conf
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper
    ports:
      - 2181:2181
```

And this `.env` file:

```shell
KAFKA_ADVERTISED_HOST=kafka
KAFKA_ADVERTISED_PORT=9092
KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
KAFKA_LISTENERS=SASL_PLAINTEXT://:9092
KAFKA_SASL_ENABLED_MECHANISMS=SCRAM-SHA-256,SCRAM-SHA-512
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=SASL_PLAINTEXT:SASL_PLAINTEXT
KAFKA_INTER_BROKER_LISTENER_NAME=SASL_PLAINTEXT
KAFKA_ADVERTISED_LISTENERS=SASL_PLAINTEXT://kafka:9092
KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SCRAM-SHA-256
KAFKA_OPTS="-Djava.security.auth.login.config=/app/config/jaas.conf"
```

But I get this error when I try to execute `docker compose up` command in my terminal:

```shell
[+] Running 0/2
 ⠙ zookeeper Pulling                                                                                            2.2s 
 ⠙ kafka Pulling                                                                                                2.2s 
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/wurstmeister/zookeeper:3.4.6 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```
