### ISSUE TITLE
Create a new release 3.4.9

### ISSUE THREAD

**Issue by ahderman** [wurstmeister/zookeeper-docker#8]
Would it be possible to create a new release, now that the version has been bumped to 3.4.9?

**Comment by peanutpi** [comment]
Please release a new docker with tag **3.4.9**. We are persisting data on host machine for zookeeper docker container.

```yml
  zookeeper:
    image: docker.dreamworld.solutions/wurstmeister/zookeeper:latest
    volumes:
    - ./zookeeperData:/opt/zookeeper-3.4.9/data/version-2
    ports:
    - 2181:2181
```
- so please release a new docker container so that we can use that one instead of **latest**.
